version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: crispr-postgres
    environment:
      POSTGRES_DB: crispr_db
      POSTGRES_USER: crispr_user
      POSTGRES_PASSWORD: crispr_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./packages/db/migrations:/docker-entrypoint-initdb.d/migrations:ro
    networks:
      - crispr_network
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U crispr_user -d crispr_db']
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crispr-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crispr.local
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '5050:80'
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - crispr_network
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  crispr_network:
    driver: bridge
