apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: nanopore-tracking-app
  labels:
    app: nanopore-tracking-app
spec:
  runPolicy: Serial
  source:
    type: Binary
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: nanopore-tracking-app:latest
  triggers:
  - type: ConfigChange
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nanopore-tracking-app
  labels:
    app: nanopore-tracking-app