---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nanopore-tracking-sa
  namespace: dept-barc
  labels:
    app: nanopore-tracking-app
    version: v1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nanopore-tracking-role
  namespace: dept-barc
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/log", "pods/status"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nanopore-tracking-rolebinding
  namespace: dept-barc
subjects:
- kind: ServiceAccount
  name: nanopore-tracking-sa
  namespace: dept-barc
roleRef:
  kind: Role
  name: nanopore-tracking-role
  apiGroup: rbac.authorization.k8s.io 